<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Principal Components Analysis – Advanced Statistical Methods for Analyzing Empirical Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ma1.html" rel="next">
<link href="./linear2.html" rel="prev">
<link href="./images/cover.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<link href="site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">

<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">

<script src="site_libs/datatables-binding-0.33/datatables.js"></script>

<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>

<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">

<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">

<script src="site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>

<link href="site_libs/dt-ext-scroller-1.13.6/css/scroller.dataTables.min.css" rel="stylesheet">

<script src="site_libs/dt-ext-scroller-1.13.6/js/dataTables.scroller.min.js"></script>

<link href="site_libs/dt-ext-buttons-1.13.6/css/buttons.dataTables.min.css" rel="stylesheet">

<script src="site_libs/dt-ext-buttons-1.13.6/js/dataTables.buttons.min.js"></script>

<script src="site_libs/dt-ext-buttons-1.13.6/js/buttons.html5.min.js"></script>

<script src="site_libs/dt-ext-buttons-1.13.6/js/buttons.colVis.min.js"></script>

<script src="site_libs/dt-ext-buttons-1.13.6/js/buttons.print.min.js"></script>

<link href="site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">

<script src="site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./pca.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Principal Components Analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Advanced Statistical Methods for Analyzing Empirical Data</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome!</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Jamovi and data preparation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">ANOVA Designs (1)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">ANOVA Designs (2)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">ANOVA Designs (3)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Linear regression (1)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Linear regression (2)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pca.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Principal Components Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ma1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Systematic Review and Meta-analysis (1)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ma2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Systematic Review and Meta-analysis (2)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./presentations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Presentations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">7.1</span> Introduction</a></li>
  <li><a href="#the-technical-part-eigen-decomposition" id="toc-the-technical-part-eigen-decomposition" class="nav-link" data-scroll-target="#the-technical-part-eigen-decomposition"><span class="header-section-number">7.2</span> The technical part: eigen decomposition</a>
  <ul class="collapse">
  <li><a href="#pc1" id="toc-pc1" class="nav-link" data-scroll-target="#pc1"><span class="header-section-number">7.2.1</span> PC1</a></li>
  <li><a href="#pc2" id="toc-pc2" class="nav-link" data-scroll-target="#pc2"><span class="header-section-number">7.2.2</span> PC2</a></li>
  </ul></li>
  <li><a href="#eigenvalues-and-variance" id="toc-eigenvalues-and-variance" class="nav-link" data-scroll-target="#eigenvalues-and-variance"><span class="header-section-number">7.3</span> Eigenvalues and variance</a></li>
  <li><a href="#steps-in-the-process-of-pca" id="toc-steps-in-the-process-of-pca" class="nav-link" data-scroll-target="#steps-in-the-process-of-pca"><span class="header-section-number">7.4</span> Steps in the process of PCA</a></li>
  <li><a href="#example-of-grms-stress-appraisal" id="toc-example-of-grms-stress-appraisal" class="nav-link" data-scroll-target="#example-of-grms-stress-appraisal"><span class="header-section-number">7.5</span> Example of GRMS Stress Appraisal</a>
  <ul class="collapse">
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions"><span class="header-section-number">7.5.1</span> Assumptions</a></li>
  <li><a href="#specify-the-number-of-components" id="toc-specify-the-number-of-components" class="nav-link" data-scroll-target="#specify-the-number-of-components"><span class="header-section-number">7.5.2</span> Specify the Number of Components</a></li>
  <li><a href="#component-rotation" id="toc-component-rotation" class="nav-link" data-scroll-target="#component-rotation"><span class="header-section-number">7.5.3</span> Component Rotation</a></li>
  </ul></li>
  <li><a href="#varimax-rotation" id="toc-varimax-rotation" class="nav-link" data-scroll-target="#varimax-rotation"><span class="header-section-number">7.6</span> Varimax rotation</a></li>
  <li><a href="#oblique-rotation" id="toc-oblique-rotation" class="nav-link" data-scroll-target="#oblique-rotation"><span class="header-section-number">7.7</span> Oblique rotation</a></li>
  <li><a href="#component-scores" id="toc-component-scores" class="nav-link" data-scroll-target="#component-scores"><span class="header-section-number">7.8</span> Component scores</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-pca" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Principal Components Analysis</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>When we have finished this chapter, we should be able to:</p>
<div class="callout callout-style-default callout-caution no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Learning objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Understand when and why to use Principal Component Analysis (PCA), and recognize appropriate data conditions</li>
<li>Understand the concept of eigen decomposition</li>
<li>Perform PCA through a step-by-step process</li>
<li>Interpret component loadings and the proportion of explained variance</li>
<li>Extract and interpret component scores for further analysis</li>
</ul>
</div>
</div>
<section id="introduction" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">7.1</span> Introduction</h2>
<p>Principal Component Analysis (PCA) is a statistical technique used to reduce the dimensionality of a dataset while preserving as much of its original variability as possible. It transforms a large set of correlated variables into a smaller set of representative variables, called principal components, which collectively explain most of the variability in the original data.</p>
<p>Suppose that we have <span class="math inline">\(n\)</span> observations with measurements on a set of <span class="math inline">\(p\)</span> observed variables (features), <span class="math inline">\(X_1,X_2, . . . ,X_p\)</span>. This means that each of the <span class="math inline">\(n\)</span> observations lives in p-dimensional space, but not all of these dimensions are equally interesting.</p>
<p>PCA seeks a small number of dimensions that are as interesting as possible, where the concept of interesting is measured by the amount that the observations vary along each dimension. Each of the dimensions found by PCA is a linear combination of the <span class="math inline">\(p\)</span> observed variables. We now explain the manner in which these dimensions, or principal components, are found.</p>
<p>The first principal component of a set of observed variables <span class="math inline">\(X_1, X_2, . . . ,X_p\)</span> is the normalized linear combination of the observed variables:</p>
<p><span class="math display">\[PC1: Z_1 = \phi_{11} X_1 + \phi_{21} X_2  + ...+ \phi_{p1} X_p \]</span> that has the largest variance. By normalized, we mean that <span class="math inline">\(\sum_{j=1}^p \phi_{j1}^2 = 1\)</span>. We refer to the elements <span class="math inline">\(\phi_{11}, \phi_{21},..., \phi_{p1}\)</span> as the loadings of the first principal component.</p>
<p>To obtain the loadings of the first principal component (PC1), we solve an optimization problem that maximizes the variance of the data projected onto a linear combination of the original variables. This can be solved via an <strong>eigen decomposition</strong>, a standard technique in linear algebra (algebra of matrices).</p>
<p>After the first principal component <span class="math inline">\(Z_1\)</span> of the observed variables has been determined, we can find the second principal component <span class="math inline">\(Z_2\)</span>.</p>
<p><span class="math display">\[PC2: Z_2 = \phi_{12} X_1 + \phi_{22} X_2  + ...+ \phi_{p2} X_p \]</span></p>
<p>The second principal component (PC2) explaines the next highest amount of variance. The elements <span class="math inline">\(\phi_{12}, \phi_{22},..., \phi_{p2}\)</span> are referred to as the loadings of the second principal component.</p>
<p>The same procedure can be applied to obtain the third principal component (PC3), the fourth component (PC4) and so on for subsequent components.</p>
<p><strong>EXAMPLE DATA</strong></p>
<p>Our data analysis is based on the paper published by Lewis and Neville on the Gendered Racial Microaggressions Scale for Black Women. The article presents two separate studies that contributed to the development, refinement, and psychometric evaluation of two parallel versions of the scale: one measuring stress appraisal and the other measuring frequency. For the purposes of our analysis, we focus on the final construction of the stress appraisal version. Items were rated on a 6-point Likert scale ranging from 0 (not at all stressful) to 5 (extremely stressful).</p>
<div class="cell">
<div id="fig-dfGRMS0" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dfGRMS0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="datatables html-widget html-fill-item" id="htmlwidget-5948e4104212b4df047e" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-5948e4104212b4df047e">{"x":{"filter":"none","vertical":false,"extensions":["Scroller","Buttons"],"data":[[2,4,2,4,3,2,3,2,2,3,2,4,1,2,3,4,3,3,2,3,3,3,2,3,2,4,0,2,2,3,2,1,3,2,3,4,3,2,4,3,4,4,3,1,3,3,3,4,3,2,3,3,3,3,4,3,1,3,4,2,3,3,4,2,3,2,3,2,4,3,3,4,3,3,2,4,3,3,3,3,3,2,3,3,3,3,3,1,4,3,3,4,4,4,2,3,3,3,2,4,2,3,5,3,4,5,3,2,4,1,2,3,3,2,3,3,1,3,2,3,2,3,3,4,4,2,3,2,2,2,3,4,3,3,3,2,5,3,4,1,3,3,3,4,3,3,2,3,3,2,3,3,3,3,2,3,2,4,3,3,1,2,1,2,3,3,3,3,3,3,3,3,2,2,2,2,3,1,3,2,2,1,3,3,4,3,4,1,3,1,3,2,4,2,3,2,3,2,4,3,1,4,3,2,2,4,1,3,2,4,2,3,3,3,3,3,4,2,3,2,3,4,2,2,2,3,2,3,4,3,3,3,2,3,2,1,3,3,3,0,2,4,3,3,2,2,3,3,3,3,3,3,2,3,3,2,4,4,2],[1,3,3,3,2,3,2,1,3,1,2,3,2,2,3,3,3,2,2,3,2,2,3,3,2,5,2,3,2,2,2,2,3,1,3,3,2,3,5,2,3,4,4,0,2,3,3,2,2,2,4,3,3,1,5,2,2,1,4,2,2,3,3,1,3,3,4,4,3,2,3,3,3,3,2,3,3,4,2,3,2,3,3,2,1,3,3,2,3,3,2,3,2,3,3,3,4,2,3,3,2,3,3,3,4,5,3,3,3,2,3,4,2,2,3,3,2,3,2,3,2,2,4,2,4,2,2,3,3,2,3,3,1,3,4,2,2,4,3,2,2,3,0,3,3,3,3,2,1,1,2,3,3,2,3,3,2,4,5,3,1,2,3,2,2,3,4,4,3,2,3,3,2,2,2,4,5,2,3,3,4,3,3,4,3,2,2,2,3,2,3,2,2,2,2,2,1,2,4,3,2,3,2,2,4,3,4,2,2,3,2,2,3,2,2,2,4,2,3,4,3,3,3,3,1,3,2,3,3,5,3,3,2,2,2,2,3,4,4,2,1,1,3,3,3,1,4,2,4,3,4,2,2,4,3,1,2,3,1],[1,2,4,2,3,2,2,2,2,3,3,2,3,2,3,4,3,3,3,3,2,2,2,2,3,4,1,2,2,4,4,0,2,1,4,2,3,2,3,3,2,5,2,0,1,2,2,5,3,3,3,2,3,3,5,3,2,2,3,1,2,1,3,2,3,4,3,3,2,2,3,3,4,3,3,5,3,3,2,2,3,3,2,2,2,3,3,2,4,3,2,4,3,1,3,4,3,3,1,4,3,4,3,3,4,5,3,3,4,2,2,4,3,2,3,2,3,3,2,4,1,2,2,3,4,3,3,0,1,1,2,0,2,2,2,3,3,3,1,4,2,3,2,2,4,3,2,3,2,1,3,1,3,2,4,1,4,3,3,1,2,2,3,3,2,4,2,2,4,2,1,2,2,2,2,3,4,3,3,2,3,4,1,2,3,3,4,3,4,3,2,1,2,3,2,3,3,3,1,2,1,3,2,1,3,3,2,1,1,4,1,2,3,1,3,2,2,4,2,3,2,4,2,3,2,4,3,3,3,3,3,2,3,3,0,3,3,3,4,3,2,2,3,1,3,1,2,2,4,3,3,2,2,4,3,3,3,4,3],[3,3,3,2,3,2,3,1,1,4,3,2,2,2,4,2,3,2,4,5,2,0,3,2,1,3,3,2,2,3,4,1,3,1,3,2,3,2,3,2,5,5,2,1,3,2,4,3,2,3,3,3,1,3,4,3,1,3,3,3,3,2,3,2,3,4,3,2,4,2,2,5,3,3,4,5,2,3,4,2,1,2,3,2,1,1,2,1,2,3,3,3,3,4,2,4,2,2,3,4,4,4,4,3,2,1,3,4,4,2,1,2,1,2,2,4,1,4,2,2,3,2,3,4,3,2,2,4,2,1,2,2,3,2,4,2,2,3,2,3,3,2,2,5,2,3,3,3,2,3,2,3,1,2,1,4,4,4,4,3,2,2,2,3,3,4,2,2,4,2,3,4,3,1,3,2,4,2,1,3,5,4,4,1,3,3,4,4,3,2,3,1,2,3,3,2,3,3,2,2,3,5,3,3,4,3,3,2,1,4,2,1,2,2,1,4,2,1,4,2,2,3,1,3,1,5,4,0,4,3,3,2,1,2,1,1,3,3,2,2,1,3,2,2,3,2,5,3,2,3,2,3,1,4,3,1,3,3,2],[2,2,3,3,4,1,4,2,2,1,5,2,3,2,3,4,2,4,3,4,2,2,2,3,1,4,1,0,2,3,3,1,2,0,3,2,1,2,3,2,3,4,2,1,1,3,3,3,0,2,3,1,1,4,4,1,1,3,2,2,1,3,4,1,2,3,2,2,3,2,3,2,2,2,2,3,2,4,3,2,2,2,2,2,2,2,3,1,1,3,3,1,2,3,3,2,1,2,2,4,1,3,3,3,2,3,1,3,3,1,2,3,1,2,3,2,1,3,2,3,3,2,3,5,2,2,2,3,1,2,3,2,3,2,3,3,1,3,2,4,2,2,2,2,2,3,1,2,2,2,1,2,3,3,3,4,2,4,2,4,1,3,2,4,3,3,2,2,2,2,3,3,1,2,2,2,3,1,2,1,3,3,3,1,3,3,2,2,2,2,2,2,3,1,3,3,3,1,3,3,3,3,2,2,3,4,3,2,0,3,1,2,4,2,2,2,4,2,3,3,2,2,2,3,3,4,3,2,3,2,3,2,3,1,1,1,2,1,4,3,2,3,1,2,3,2,3,2,4,2,2,1,0,4,2,2,3,3,2],[2,3,4,0,3,2,2,1,1,4,3,3,2,2,2,3,2,3,3,4,3,2,2,4,3,5,3,4,2,2,3,1,1,3,5,2,4,2,3,2,2,3,1,1,1,4,3,3,2,2,4,2,2,3,4,2,3,2,3,1,3,1,2,1,3,2,2,3,1,2,2,4,2,2,2,3,3,3,3,1,3,3,2,0,2,2,3,3,1,2,2,4,3,2,3,1,3,2,1,3,3,2,3,3,3,3,3,3,3,1,2,2,1,2,2,1,3,2,3,3,3,1,2,3,3,4,3,2,3,3,2,2,2,2,2,2,3,4,2,2,2,2,2,4,2,4,2,3,2,1,1,2,1,3,3,3,2,4,3,3,2,1,1,2,2,3,4,2,4,3,3,2,2,2,3,3,3,2,4,1,4,2,5,3,2,3,4,2,2,1,3,1,2,3,2,0,3,3,3,3,2,4,2,2,3,3,2,2,1,3,1,3,1,2,2,2,3,3,1,2,3,4,3,2,2,2,2,3,3,1,3,1,3,3,2,2,3,3,2,1,1,3,2,3,3,2,3,1,1,1,4,3,2,2,2,3,3,2,2],[2,3,3,1,1,4,1,3,2,2,2,4,2,2,4,1,1,1,4,4,1,2,2,2,0,4,1,3,2,0,5,3,1,2,3,5,3,2,3,4,2,4,2,1,4,3,4,2,3,1,2,2,0,1,3,2,2,2,5,1,2,2,3,1,3,2,4,2,3,2,4,5,2,3,3,4,3,5,3,2,4,3,2,0,4,2,2,1,3,5,2,3,2,2,4,3,3,3,2,4,3,0,3,4,4,5,1,3,3,1,1,3,1,1,2,2,3,4,1,1,1,2,5,3,4,3,1,3,1,3,2,2,3,3,4,1,2,1,2,2,3,1,3,3,3,3,2,2,2,5,2,3,3,3,3,2,3,2,4,4,0,3,2,2,3,3,2,4,3,3,1,3,5,2,3,2,3,1,4,2,3,2,3,2,5,2,5,4,2,2,0,2,2,2,4,2,3,2,3,4,3,4,5,1,3,5,2,2,1,3,0,1,2,3,1,2,1,2,2,5,2,3,3,2,2,2,2,2,2,3,3,3,1,2,1,2,3,4,3,1,1,1,3,3,3,1,3,4,3,0,2,1,4,5,3,0,3,4,2],[1,2,1,1,2,2,3,3,3,2,3,3,1,2,3,3,1,2,3,3,1,2,3,3,3,3,2,2,1,3,4,2,3,0,2,4,3,2,3,3,3,3,2,2,2,2,2,4,2,2,4,2,2,3,3,2,1,2,4,3,3,2,5,2,2,3,2,3,3,2,1,4,2,1,2,3,3,4,3,2,2,3,3,2,3,2,4,2,3,2,1,2,2,3,3,2,2,2,3,4,2,3,3,3,4,5,3,3,4,3,1,2,3,1,3,3,2,2,2,3,2,1,2,3,3,2,2,3,2,1,4,3,3,3,3,2,3,3,3,4,3,2,3,3,3,4,2,3,1,2,3,4,3,1,2,2,3,2,3,4,1,3,2,3,1,2,2,4,4,2,2,3,3,1,1,2,3,1,3,2,4,2,2,3,4,3,4,3,3,2,2,2,3,3,3,3,3,2,3,2,3,4,3,2,3,2,2,3,0,2,3,2,3,2,2,3,3,2,3,1,1,3,2,2,3,2,2,4,2,3,3,3,3,0,0,3,3,3,2,1,1,2,3,2,3,3,4,3,3,2,1,3,1,2,3,2,2,3,1],[4,2,5,2,1,2,3,1,2,3,2,3,2,3,4,3,3,2,3,3,3,4,2,4,3,5,2,2,3,3,2,1,3,1,2,4,4,4,5,2,3,3,1,1,3,3,3,2,1,3,3,3,2,2,5,3,3,2,3,3,2,3,4,2,1,4,2,2,2,4,3,3,3,3,1,2,1,4,3,3,3,3,3,2,3,1,4,2,2,3,2,3,2,3,4,3,3,1,2,4,0,3,3,3,3,2,1,2,3,1,3,3,2,2,3,3,4,2,1,3,2,2,4,3,2,4,3,3,4,1,2,2,3,1,3,2,1,2,2,2,3,3,1,3,4,4,3,2,3,1,2,1,2,3,3,2,2,4,2,3,2,2,2,3,2,4,3,4,4,2,2,4,4,2,3,3,3,3,2,2,4,4,2,1,3,2,3,4,4,2,2,2,3,3,3,1,3,3,3,3,4,5,4,2,3,3,1,3,2,3,3,2,4,2,2,4,2,3,4,2,3,2,3,3,1,3,3,2,1,2,2,3,2,0,2,2,3,4,4,2,3,4,4,2,3,3,3,2,2,4,4,2,2,4,3,4,2,4,2],[3,3,2,1,2,3,3,2,2,3,2,3,2,2,4,2,1,2,2,2,2,2,2,4,2,3,2,2,2,2,2,2,2,1,3,3,3,2,3,3,2,5,2,1,3,2,3,3,2,3,2,3,1,2,3,2,1,2,2,1,1,4,3,0,2,3,4,3,2,1,3,2,3,2,3,2,3,2,3,3,2,3,3,2,2,1,1,2,2,3,2,3,2,3,3,2,2,3,2,3,3,2,2,2,3,4,2,3,3,0,1,3,2,2,1,2,2,2,1,2,2,3,2,2,2,3,3,2,3,1,3,2,3,3,1,1,2,1,2,3,3,0,3,2,3,1,3,2,2,2,3,2,3,2,2,1,3,4,2,4,1,2,3,3,3,2,1,2,3,3,1,2,2,2,2,3,2,0,1,1,3,2,2,3,2,2,2,3,3,2,1,2,2,1,1,2,2,4,2,2,2,2,2,3,3,2,2,3,2,3,3,2,2,1,1,2,3,1,3,2,3,3,1,2,2,4,3,2,2,2,3,2,2,1,1,1,3,3,2,1,2,2,1,2,1,1,4,2,3,2,4,2,2,2,3,1,2,3,2],[2,2,3,2,3,3,3,2,1,2,3,2,2,3,2,2,1,3,3,4,3,2,2,2,2,4,2,3,2,3,2,1,1,0,2,4,3,1,4,4,3,4,3,2,2,1,3,3,4,2,2,1,4,2,4,3,3,1,4,2,3,3,4,2,3,3,2,2,3,3,4,4,2,3,3,4,3,1,5,4,3,3,3,2,1,3,2,2,2,3,2,3,4,2,3,2,3,2,4,4,3,3,4,3,3,2,3,3,2,2,2,3,2,3,3,4,3,3,4,2,3,2,2,2,5,2,2,4,2,2,2,3,3,2,4,2,2,3,3,3,3,4,2,3,2,3,3,2,2,4,3,2,3,2,1,2,4,3,3,4,2,4,4,3,2,2,3,3,4,2,2,3,4,1,1,2,2,2,5,3,3,4,2,3,4,2,4,4,2,3,3,3,3,3,4,3,3,3,4,3,3,3,3,3,2,4,3,2,2,2,1,2,1,3,2,2,4,3,4,3,4,3,2,2,3,3,2,3,2,3,4,5,3,2,2,3,2,2,5,1,2,3,2,3,3,3,3,1,4,1,2,3,4,3,3,3,2,4,3],[1,2,4,1,3,3,3,3,2,3,2,4,2,3,2,3,3,2,3,4,2,4,3,3,2,4,1,3,3,4,2,1,1,1,3,4,4,1,3,2,3,4,3,3,3,3,3,3,2,2,1,2,4,3,4,3,4,2,4,2,2,2,3,3,3,3,2,3,3,2,4,4,4,5,2,4,4,2,4,3,4,2,3,3,3,2,3,1,3,2,2,3,4,4,2,2,3,3,3,3,2,3,4,4,3,3,2,1,3,2,3,4,2,4,4,4,2,3,4,1,1,2,4,3,4,2,3,2,3,2,3,2,3,3,4,3,2,3,4,3,4,3,2,3,3,3,2,3,3,3,2,3,2,3,2,3,4,5,3,5,2,3,4,2,2,2,3,2,3,3,3,1,1,1,3,1,3,3,4,3,2,3,2,4,3,2,3,4,3,3,2,3,2,2,3,2,2,3,3,3,2,4,3,2,3,3,4,2,2,3,3,3,3,2,2,2,3,3,3,3,2,3,3,3,2,3,3,1,3,2,3,3,4,3,0,2,1,2,4,3,2,3,2,2,2,3,4,2,4,1,2,3,4,3,3,2,2,3,4],[2,2,3,3,3,3,3,0,0,3,1,2,2,4,2,4,2,0,3,4,2,3,3,3,2,3,1,2,3,3,1,3,1,2,2,3,2,2,4,4,1,4,2,2,4,3,2,3,4,1,2,1,3,3,5,3,3,2,2,3,1,2,3,1,2,3,3,3,2,2,3,3,3,3,2,4,3,3,4,1,2,1,4,1,1,3,3,1,2,4,3,2,4,4,3,1,2,1,4,3,2,1,4,3,2,3,1,1,3,2,1,4,2,3,2,3,3,3,1,0,1,3,2,1,3,2,3,2,3,1,2,0,2,3,4,3,2,1,2,2,3,2,2,2,0,3,3,2,2,3,3,1,3,3,2,2,3,4,2,3,1,3,2,3,1,1,4,3,4,2,3,2,3,1,2,4,3,2,4,2,2,3,1,3,2,2,2,3,3,2,2,3,4,3,3,4,2,2,3,2,3,2,0,3,4,3,3,3,1,2,1,1,2,2,1,3,5,2,3,4,3,2,3,2,2,3,3,1,3,2,3,5,4,0,1,2,1,2,5,2,0,3,4,2,2,2,1,2,4,2,1,2,2,3,2,4,3,4,1],[2,2,2,1,4,2,4,3,3,2,3,2,2,3,2,3,2,2,4,3,1,2,2,3,2,2,1,1,2,2,3,2,2,1,3,2,2,3,3,2,3,4,1,0,4,2,2,2,4,1,2,1,3,4,3,3,2,2,2,2,3,2,3,2,3,3,2,2,3,1,2,3,2,3,3,4,2,2,5,2,2,3,2,1,1,3,2,2,2,3,2,3,3,2,3,3,3,2,3,3,3,3,4,3,3,4,3,2,3,3,1,3,3,3,4,2,2,4,3,1,1,2,3,1,3,2,3,4,2,3,2,2,2,2,3,3,4,3,2,3,3,2,2,3,1,2,1,3,3,3,3,2,3,2,2,2,2,3,3,2,0,2,2,2,2,2,2,3,3,1,1,3,3,1,3,2,3,1,4,2,3,4,3,1,4,2,2,3,2,2,3,2,2,2,3,2,2,2,2,2,3,4,2,3,3,3,1,3,4,3,3,3,1,1,1,2,3,2,3,3,3,3,3,0,2,3,3,2,2,2,3,4,4,3,1,3,2,3,4,2,2,1,2,3,3,4,3,2,4,3,2,1,3,4,3,3,2,3,2],[2,3,3,2,3,3,2,2,1,2,4,3,1,4,1,5,1,1,2,5,3,2,2,2,1,2,1,2,3,3,3,1,1,1,3,2,2,0,3,1,2,3,2,1,3,1,4,2,1,3,2,2,3,2,4,3,2,1,3,2,3,1,3,1,2,3,3,3,3,3,3,3,3,3,3,2,2,1,4,3,2,2,2,2,2,2,1,2,3,2,2,2,2,3,3,3,2,2,3,3,2,2,3,5,3,3,1,1,3,2,2,3,2,2,2,2,2,2,3,3,2,1,3,2,3,2,1,3,1,4,1,2,3,2,2,2,2,3,3,4,3,3,1,2,2,3,2,2,3,1,2,2,2,4,1,3,3,1,3,4,1,1,3,2,3,2,2,3,3,2,2,1,2,0,1,1,2,2,4,3,3,3,2,2,2,2,3,4,4,3,2,1,3,4,4,1,1,3,4,2,3,3,2,2,2,3,2,2,2,1,2,2,2,1,2,3,2,1,3,3,2,3,2,2,2,4,2,1,3,2,3,2,3,2,1,2,1,2,4,2,1,2,3,4,3,3,4,2,3,1,3,1,2,3,2,3,1,4,3],[2,3,2,2,1,3,2,1,5,3,3,3,2,4,1,3,2,2,3,3,3,3,2,4,4,3,1,2,2,3,4,2,2,2,3,4,4,1,3,3,2,5,1,2,3,3,3,2,2,2,3,1,2,3,3,3,3,2,3,4,3,3,3,1,2,3,4,3,1,3,2,3,2,3,4,3,2,3,5,3,4,4,3,2,2,2,2,2,2,4,1,3,4,4,2,3,3,2,3,4,3,3,3,3,3,3,2,4,3,2,4,2,1,4,3,2,2,2,4,2,3,2,2,2,4,3,2,3,2,2,3,3,2,3,3,3,2,3,2,4,2,3,2,4,3,3,3,2,2,2,2,3,4,1,2,1,2,4,4,3,1,4,1,4,1,2,2,3,3,4,4,2,3,1,2,2,3,1,3,2,4,3,4,3,4,2,3,4,3,3,3,2,4,3,3,2,3,3,4,4,3,3,2,2,3,4,4,4,2,3,2,2,3,1,0,3,4,2,2,4,2,4,1,3,3,3,3,1,4,3,2,3,3,3,1,2,3,3,5,1,2,2,2,3,3,2,3,2,3,0,4,3,4,4,3,3,3,3,3],[1,1,3,1,3,3,4,1,2,3,1,3,2,3,1,1,3,2,3,3,3,4,3,3,2,4,3,3,3,3,3,3,2,1,2,3,3,1,4,2,3,4,3,2,2,1,3,4,2,3,2,2,2,3,4,4,3,1,4,2,2,2,4,2,3,3,4,2,2,1,1,4,2,3,3,5,2,1,3,4,1,3,4,2,2,3,2,2,1,2,3,4,2,3,3,3,1,2,2,3,3,2,5,3,5,1,2,3,3,2,1,2,3,2,3,2,1,2,5,1,2,2,3,2,2,2,3,3,4,1,2,2,3,3,1,3,3,2,3,2,3,3,0,3,2,2,3,1,3,0,2,3,3,4,1,2,4,3,4,5,2,1,3,2,3,5,3,3,3,4,2,1,3,1,1,2,2,0,4,3,3,3,4,4,1,0,4,4,2,3,2,1,2,1,3,3,3,3,3,4,3,4,2,1,2,2,3,1,2,1,3,1,4,3,3,3,2,2,2,3,3,3,4,3,1,3,2,2,3,4,3,3,5,4,3,3,2,2,3,2,1,2,3,1,4,3,1,3,3,1,1,2,4,3,2,3,3,3,2],[3,3,2,3,2,2,2,3,2,1,3,3,3,3,3,2,2,3,4,4,3,4,2,2,3,5,0,2,2,4,4,2,2,1,1,4,2,2,4,3,3,3,2,1,2,4,2,3,1,3,3,3,3,3,4,2,4,4,3,1,2,3,3,3,3,3,3,2,1,2,4,3,3,5,1,3,4,4,3,3,3,2,2,2,4,2,2,1,3,2,4,3,3,4,4,3,4,4,3,2,2,2,3,5,3,4,1,4,2,2,3,2,4,2,2,2,2,2,3,1,2,1,5,2,2,3,2,2,2,3,2,3,4,2,5,3,2,2,2,2,2,4,3,2,2,3,3,4,3,3,3,2,2,3,2,3,4,4,2,4,1,3,3,3,2,2,3,5,2,3,5,3,3,3,2,2,3,0,3,2,3,4,2,4,3,1,4,4,3,3,2,2,3,3,3,3,4,3,2,1,2,4,2,4,3,3,2,2,3,2,2,2,4,2,2,2,4,3,2,3,2,3,4,2,3,3,2,3,4,4,4,3,2,3,3,2,4,3,3,2,3,3,3,2,2,3,2,2,4,3,2,3,2,2,3,3,2,3,2],[3,2,4,2,1,2,3,2,3,4,3,3,2,3,3,2,3,2,4,3,4,4,3,3,3,2,2,3,2,3,3,2,3,1,3,3,3,3,1,1,2,3,3,1,3,2,2,2,3,2,2,3,2,3,4,2,3,2,2,1,4,2,2,0,2,3,1,1,2,3,4,3,2,4,2,2,4,2,4,2,2,2,3,2,3,3,3,2,2,5,3,3,3,4,3,4,4,4,2,3,3,4,3,2,1,4,3,3,4,2,2,4,2,4,2,3,3,2,3,3,1,3,3,3,2,2,2,2,3,2,2,2,3,3,2,2,2,3,2,3,3,1,1,3,4,1,4,2,3,2,3,2,1,4,2,3,2,4,3,2,1,3,2,2,2,3,2,3,2,2,3,4,3,2,2,2,5,1,3,3,2,3,2,3,3,2,3,3,2,0,2,1,2,4,2,3,3,2,3,2,1,5,2,4,3,4,4,3,2,2,2,3,3,1,1,3,4,3,3,3,2,3,3,0,3,3,2,3,4,3,2,3,2,3,3,4,3,3,3,3,1,4,2,2,2,2,4,2,4,3,3,2,3,2,3,3,3,5,3],[3,4,2,3,2,3,2,4,2,1,2,4,4,2,1,2,3,2,4,3,2,1,3,0,3,4,2,3,4,1,2,3,3,1,2,3,2,1,2,3,2,2,3,1,2,2,1,2,2,2,3,2,3,2,1,3,3,4,2,3,2,3,4,0,1,1,3,1,1,3,5,2,2,4,3,1,2,3,2,1,4,2,2,0,3,2,3,0,0,3,2,3,3,2,2,4,3,3,2,2,2,3,2,3,2,4,1,2,3,1,4,2,1,1,2,2,2,2,2,1,1,1,2,3,4,1,3,1,3,2,1,2,2,3,3,2,2,2,2,2,2,2,1,4,2,2,3,3,3,2,2,2,2,3,2,4,5,4,1,4,2,2,3,2,3,3,2,4,3,1,2,1,2,2,2,2,2,2,3,1,3,3,2,3,3,1,3,4,2,2,1,2,2,3,2,2,4,3,2,1,3,3,2,4,1,3,2,2,2,2,2,2,4,1,2,3,4,2,1,2,3,4,1,1,2,3,2,3,4,2,1,2,2,2,1,4,2,1,4,2,2,3,3,3,3,3,3,2,1,2,3,2,2,3,3,1,1,2,4],[4,3,1,2,2,2,1,1,2,3,3,1,2,3,2,2,2,3,3,3,3,2,2,1,3,3,2,2,3,2,2,2,3,2,2,3,2,2,2,3,3,2,2,2,2,2,2,3,3,2,3,3,2,2,4,1,3,3,2,2,2,2,2,1,2,3,2,2,3,3,3,3,2,4,1,2,3,3,2,1,3,2,2,1,3,3,2,2,2,2,2,2,3,2,2,3,3,2,2,2,2,2,2,3,3,3,2,3,3,3,2,1,2,3,1,2,1,3,2,4,1,2,3,1,3,1,2,2,1,3,2,1,2,1,2,3,3,2,3,2,1,2,1,3,4,2,3,3,2,0,2,3,2,1,2,2,5,3,4,3,2,2,2,3,1,2,2,2,1,2,2,2,2,2,2,1,2,3,2,0,2,3,3,2,3,2,4,3,2,2,3,2,2,2,4,2,2,2,2,2,2,3,1,4,2,2,3,3,2,2,2,3,4,1,2,3,3,3,2,2,2,2,2,1,2,4,2,2,2,2,2,3,2,2,2,3,1,1,3,3,2,2,4,1,2,1,4,2,4,1,2,2,1,2,2,1,2,1,2],[1,4,3,1,2,2,2,2,2,2,3,4,3,2,3,3,4,3,3,4,3,3,4,2,1,3,1,2,4,4,2,3,2,2,1,1,3,3,2,2,4,4,2,1,1,4,4,2,3,2,3,4,4,2,4,1,4,2,4,1,1,4,4,1,3,2,3,0,2,2,4,3,3,4,0,3,1,3,4,2,2,1,2,2,3,1,2,1,3,3,3,1,3,2,1,3,2,2,2,2,2,3,3,3,3,5,2,3,3,2,1,1,2,1,0,2,2,1,4,2,3,4,3,4,3,2,3,0,2,1,1,3,4,4,3,3,4,3,2,3,2,4,2,1,2,4,3,3,4,3,1,1,2,2,3,2,3,3,3,3,1,2,3,3,4,2,2,2,4,4,3,1,2,4,2,1,2,3,2,2,3,3,2,4,4,0,3,3,2,4,2,4,2,4,3,2,2,1,2,3,4,3,3,1,2,2,4,2,2,3,3,4,1,2,3,3,4,1,2,3,3,2,3,1,4,3,1,3,4,3,2,2,4,3,2,2,1,3,3,3,1,3,3,2,2,1,4,3,3,2,4,2,3,4,1,3,4,4,2],[2,1,3,3,2,3,2,5,3,3,2,3,4,4,3,2,4,3,2,4,1,3,3,2,2,4,2,3,3,3,3,2,2,2,3,3,3,2,3,2,3,3,2,3,3,4,1,3,2,2,3,3,3,2,3,2,2,2,3,3,3,4,4,2,1,2,3,1,3,4,4,2,3,3,1,4,3,2,3,2,3,2,3,1,3,2,3,2,3,4,3,2,4,3,2,3,2,2,3,3,3,1,4,4,3,2,3,2,4,3,2,2,2,4,3,4,1,2,4,3,3,1,3,2,2,3,3,2,4,3,3,1,5,5,3,1,1,1,1,2,2,3,1,4,1,1,3,0,2,3,0,2,2,4,3,1,4,4,2,2,1,3,4,2,3,2,2,2,3,2,3,2,3,2,1,1,3,3,1,1,5,4,4,3,3,1,4,3,3,3,2,3,1,3,4,2,3,2,2,3,4,4,1,2,2,5,2,3,2,4,4,2,3,1,4,0,4,4,2,1,2,1,3,1,2,3,1,1,3,1,3,4,4,2,3,4,2,3,3,2,3,2,5,2,1,2,3,2,3,2,2,0,3,2,3,2,2,5,1],[2,3,3,1,3,3,2,3,3,1,2,2,2,2,1,3,3,1,1,3,3,3,3,2,2,3,1,4,3,3,3,2,1,2,2,3,3,4,3,1,0,4,0,3,2,4,2,3,3,3,3,1,3,2,3,2,3,2,1,1,3,1,3,2,1,3,3,2,2,0,3,1,2,3,2,3,3,1,5,1,2,1,0,1,0,5,2,1,2,3,2,2,4,1,3,2,2,1,4,2,3,3,3,3,4,3,1,3,3,1,2,2,3,2,1,2,1,4,2,1,4,1,3,2,2,1,2,2,5,2,3,2,3,3,1,1,3,3,2,3,2,2,3,4,2,1,3,2,1,3,1,0,2,5,3,1,1,4,4,3,1,4,3,1,3,2,1,3,1,2,2,2,1,1,3,2,3,2,2,1,3,4,5,2,1,1,2,2,2,2,2,4,1,2,3,3,2,2,2,3,2,1,1,3,2,3,3,4,2,2,3,3,0,3,1,2,2,3,2,1,2,3,3,3,1,3,1,2,2,2,2,3,1,3,1,2,1,3,4,1,1,2,2,3,4,1,3,1,2,0,3,2,3,3,2,2,4,4,3],[2,2,2,1,2,3,1,4,3,3,3,3,2,2,2,3,3,4,2,3,3,4,3,2,2,2,2,3,3,2,2,2,2,2,2,4,3,1,2,2,3,5,1,1,3,2,3,3,3,2,2,2,3,2,4,1,3,2,1,0,3,1,3,4,2,2,3,2,3,4,4,2,3,1,2,3,2,2,3,3,2,2,2,1,2,2,3,1,2,3,1,2,3,2,3,3,2,3,3,3,3,2,4,4,2,3,3,1,1,1,3,3,1,3,2,2,0,5,2,2,4,1,3,2,3,0,2,3,3,2,2,3,3,3,2,1,2,2,0,2,4,3,3,3,2,3,2,3,3,2,2,2,2,2,1,4,2,2,3,3,3,3,3,1,4,2,3,3,4,1,2,2,2,1,2,2,3,3,3,2,3,2,2,3,3,1,3,3,3,2,2,2,2,3,2,2,3,2,3,2,1,4,2,2,4,5,2,2,3,3,2,2,3,3,2,1,3,3,2,1,3,3,3,2,2,2,2,2,1,1,3,3,3,2,3,3,2,2,3,2,0,3,1,3,1,1,2,2,3,1,3,3,3,4,4,1,3,3,3]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th>Obj1<\/th>\n      <th>Obj2<\/th>\n      <th>Obj3<\/th>\n      <th>Obj4<\/th>\n      <th>Obj5<\/th>\n      <th>Obj6<\/th>\n      <th>Obj7<\/th>\n      <th>Obj8<\/th>\n      <th>Obj9<\/th>\n      <th>Obj10<\/th>\n      <th>Marg1<\/th>\n      <th>Marg2<\/th>\n      <th>Marg3<\/th>\n      <th>Marg4<\/th>\n      <th>Marg5<\/th>\n      <th>Marg6<\/th>\n      <th>Marg7<\/th>\n      <th>Str1<\/th>\n      <th>Str2<\/th>\n      <th>Str3<\/th>\n      <th>Str4<\/th>\n      <th>Str5<\/th>\n      <th>Ang1<\/th>\n      <th>Ang2<\/th>\n      <th>Ang3<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"deferRender":false,"dom":"Bt","scrollY":452,"scroller":true,"scrollX":true,"pageLength":10,"buttons":[{"extend":"csv","filename":"dfGRMS"}],"columnDefs":[{"className":"dt-right","targets":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]},{"name":"Obj1","targets":0},{"name":"Obj2","targets":1},{"name":"Obj3","targets":2},{"name":"Obj4","targets":3},{"name":"Obj5","targets":4},{"name":"Obj6","targets":5},{"name":"Obj7","targets":6},{"name":"Obj8","targets":7},{"name":"Obj9","targets":8},{"name":"Obj10","targets":9},{"name":"Marg1","targets":10},{"name":"Marg2","targets":11},{"name":"Marg3","targets":12},{"name":"Marg4","targets":13},{"name":"Marg5","targets":14},{"name":"Marg6","targets":15},{"name":"Marg7","targets":16},{"name":"Str1","targets":17},{"name":"Str2","targets":18},{"name":"Str3","targets":19},{"name":"Str4","targets":20},{"name":"Str5","targets":21},{"name":"Ang1","targets":22},{"name":"Ang2","targets":23},{"name":"Ang3","targets":24}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dfGRMS0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.1: Table with raw data.
</figcaption>
</figure>
</div>
</div>
<p>Lewis and Neville provided support for both a total scale score, consisting of 25 items, and four subscales. Below, we outline the four subscales, including the number of items in each, their abbreviations, and a sample item representing each subscale:</p>
<ul>
<li>Assumptions of Beauty and Sexual Objectification (10 items)
<ul>
<li>Unattractive because of size of butt (Obj1)</li>
<li>Negative comments about size of facial features (Obj2)</li>
<li>Imitated the way they think Black women speak (Obj3)</li>
<li>Someone made me feel unattractive (Obj4)</li>
<li>Negative comment about skin tone (Obj5)</li>
<li>Someone assumed I speak a certain way (Obj6)</li>
<li>Objectified me based on physical features(Obj7)</li>
<li>Someone assumed I have a certain body type (Obj8)</li>
<li>Made a sexually inappropriate comment (Obj9)</li>
<li>Negative comments about my hair when natural (Obj10)</li>
</ul></li>
<li>Silenced and Marginalized (7 items)
<ul>
<li>I have felt unheard (Marg1)</li>
<li>My comments have been ignored (Marg2)</li>
<li>Someone challenged my authority (Marg3)</li>
<li>I have been disrespected in workplace (Marg4)</li>
<li>Someone has tried to “put me in my place” (Marg5)</li>
<li>Felt excluded from networking opportunities (Marg6)</li>
<li>Assumed I did not have much to contribute to the conversation (Marg7)</li>
</ul></li>
<li>Strong Black Woman Stereotype (5 items)
<ul>
<li>Someone assumed I was sassy and straightforward (Str1)</li>
<li>I have been told that I am too independent (Str2)</li>
<li>Someone made me feel exotic as a Black woman (Str3)</li>
<li>I have been told that I am too assertive (Str4)</li>
<li>Assumed to be a strong Black woman (Str5)</li>
</ul></li>
<li>Angry Black Woman Stereotype (3 items)
<ul>
<li>Someone has told me to calm down (Ang1)</li>
<li>Perceived to be “angry Black woman” (Ang2)</li>
<li>Someone accused me of being angry when speaking calm (Ang3)</li>
</ul></li>
</ul>
</section>
<section id="the-technical-part-eigen-decomposition" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="the-technical-part-eigen-decomposition"><span class="header-section-number">7.2</span> The technical part: eigen decomposition</h2>
<div id="fig-pca0001" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pca0001-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/pca0001.png" class="img-fluid figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pca0001-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.2: Select from Factor the Principal Component Analysis.
</figcaption>
</figure>
</div>
<p><a href="#fig-pca0001" class="quarto-xref">Figure&nbsp;<span>7.2</span></a> illustrates the technical workflow of principal component analysis (PCA), as a method to reduce the number of dimensions of the data. It starts with a large table of data (<span class="math inline">\(X_{n \times p}\)</span>), standardizes it (<span class="math inline">\(X^c_{n \times p}\)</span>), and calculates the covariance matrix (<span class="math inline">\(C_{p \times p}\)</span>) between observed variables (features). Then, it finds the principal directions (eigenvectors) and their importance (eigenvalues). By selecting the most important directions (top k), the original data is projected onto a lower-dimensional space applying the projection matrix <span class="math inline">\(W_{p \times k}\)</span>, resulting in a smaller table that still captures most of the data’s variability. The scatter plots visually show this reduction from a higher to a lower dimension.</p>
<ul>
<li>R-matrix</li>
</ul>
<p>First, we calculate the R-matrix, which is a correlation matrix—a table of correlation coefficients between variables.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      Obj1 Obj2 Obj3 Obj4 Obj5 Obj6 Obj7  Obj8 Obj9 Obj10 Marg1 Marg2 Marg3
Obj1  1.00 0.35 0.25 0.27 0.28 0.25 0.28  0.35 0.15  0.24  0.19  0.25  0.17
Obj2  0.35 1.00 0.31 0.25 0.27 0.23 0.31  0.28 0.26  0.24  0.22  0.21  0.25
Obj3  0.25 0.31 1.00 0.24 0.28 0.28 0.20  0.25 0.21  0.22  0.17  0.23  0.17
Obj4  0.27 0.25 0.24 1.00 0.39 0.23 0.28  0.30 0.26  0.28  0.22  0.18  0.14
Obj5  0.28 0.27 0.28 0.39 1.00 0.15 0.18  0.29 0.25  0.20  0.17  0.20  0.23
Obj6  0.25 0.23 0.28 0.23 0.15 1.00 0.20  0.14 0.21  0.12  0.10  0.14  0.05
Obj7  0.28 0.31 0.20 0.28 0.18 0.20 1.00  0.31 0.19  0.28  0.30  0.21  0.20
Obj8  0.35 0.28 0.25 0.30 0.29 0.14 0.31  1.00 0.19  0.23  0.27  0.14  0.14
Obj9  0.15 0.26 0.21 0.26 0.25 0.21 0.19  0.19 1.00  0.20  0.10  0.12  0.21
Obj10 0.24 0.24 0.22 0.28 0.20 0.12 0.28  0.23 0.20  1.00  0.09  0.12  0.17
Marg1 0.19 0.22 0.17 0.22 0.17 0.10 0.30  0.27 0.10  0.09  1.00  0.43  0.41
Marg2 0.25 0.21 0.23 0.18 0.20 0.14 0.21  0.14 0.12  0.12  0.43  1.00  0.35
Marg3 0.17 0.25 0.17 0.14 0.23 0.05 0.20  0.14 0.21  0.17  0.41  0.35  1.00
Marg4 0.19 0.18 0.24 0.26 0.20 0.10 0.25  0.24 0.07  0.12  0.38  0.23  0.32
Marg5 0.17 0.22 0.21 0.27 0.25 0.16 0.23  0.19 0.19  0.11  0.41  0.40  0.25
Marg6 0.18 0.27 0.16 0.23 0.22 0.26 0.28  0.26 0.15  0.26  0.35  0.27  0.25
Marg7 0.13 0.19 0.14 0.19 0.06 0.17 0.16  0.14 0.10  0.11  0.31  0.33  0.20
Str1  0.22 0.18 0.14 0.06 0.23 0.07 0.25  0.17 0.19  0.10  0.19  0.25  0.20
Str2  0.19 0.18 0.19 0.19 0.12 0.15 0.13  0.06 0.18  0.19  0.12  0.18  0.17
Str3  0.10 0.09 0.09 0.08 0.11 0.09 0.19  0.05 0.12  0.10  0.13  0.18  0.10
Str4  0.09 0.14 0.18 0.15 0.12 0.08 0.07  0.13 0.05  0.02  0.08  0.12  0.08
Str5  0.20 0.15 0.15 0.08 0.19 0.11 0.15  0.04 0.07  0.09  0.10  0.23  0.12
Ang1  0.06 0.07 0.07 0.09 0.12 0.04 0.15  0.07 0.17  0.06  0.16  0.23  0.18
Ang2  0.06 0.15 0.08 0.06 0.09 0.20 0.13 -0.03 0.00  0.14  0.17  0.19  0.19
Ang3  0.21 0.13 0.11 0.14 0.11 0.16 0.23  0.07 0.06  0.08  0.28  0.28  0.11
      Marg4 Marg5 Marg6 Marg7 Str1 Str2 Str3 Str4 Str5 Ang1  Ang2 Ang3
Obj1   0.19  0.17  0.18  0.13 0.22 0.19 0.10 0.09 0.20 0.06  0.06 0.21
Obj2   0.18  0.22  0.27  0.19 0.18 0.18 0.09 0.14 0.15 0.07  0.15 0.13
Obj3   0.24  0.21  0.16  0.14 0.14 0.19 0.09 0.18 0.15 0.07  0.08 0.11
Obj4   0.26  0.27  0.23  0.19 0.06 0.19 0.08 0.15 0.08 0.09  0.06 0.14
Obj5   0.20  0.25  0.22  0.06 0.23 0.12 0.11 0.12 0.19 0.12  0.09 0.11
Obj6   0.10  0.16  0.26  0.17 0.07 0.15 0.09 0.08 0.11 0.04  0.20 0.16
Obj7   0.25  0.23  0.28  0.16 0.25 0.13 0.19 0.07 0.15 0.15  0.13 0.23
Obj8   0.24  0.19  0.26  0.14 0.17 0.06 0.05 0.13 0.04 0.07 -0.03 0.07
Obj9   0.07  0.19  0.15  0.10 0.19 0.18 0.12 0.05 0.07 0.17  0.00 0.06
Obj10  0.12  0.11  0.26  0.11 0.10 0.19 0.10 0.02 0.09 0.06  0.14 0.08
Marg1  0.38  0.41  0.35  0.31 0.19 0.12 0.13 0.08 0.10 0.16  0.17 0.28
Marg2  0.23  0.40  0.27  0.33 0.25 0.18 0.18 0.12 0.23 0.23  0.19 0.28
Marg3  0.32  0.25  0.25  0.20 0.20 0.17 0.10 0.08 0.12 0.18  0.19 0.11
Marg4  1.00  0.30  0.26  0.16 0.10 0.21 0.05 0.06 0.03 0.12  0.22 0.17
Marg5  0.30  1.00  0.29  0.28 0.16 0.13 0.16 0.14 0.18 0.12  0.14 0.21
Marg6  0.26  0.29  1.00  0.20 0.13 0.18 0.15 0.13 0.08 0.11  0.21 0.12
Marg7  0.16  0.28  0.20  1.00 0.14 0.05 0.04 0.02 0.12 0.17  0.13 0.09
Str1   0.10  0.16  0.13  0.14 1.00 0.21 0.30 0.23 0.23 0.18  0.05 0.10
Str2   0.21  0.13  0.18  0.05 0.21 1.00 0.20 0.20 0.12 0.16  0.12 0.16
Str3   0.05  0.16  0.15  0.04 0.30 0.20 1.00 0.27 0.18 0.20  0.07 0.15
Str4   0.06  0.14  0.13  0.02 0.23 0.20 0.27 1.00 0.12 0.15  0.03 0.02
Str5   0.03  0.18  0.08  0.12 0.23 0.12 0.18 0.12 1.00 0.22  0.15 0.11
Ang1   0.12  0.12  0.11  0.17 0.18 0.16 0.20 0.15 0.22 1.00  0.24 0.23
Ang2   0.22  0.14  0.21  0.13 0.05 0.12 0.07 0.03 0.15 0.24  1.00 0.25
Ang3   0.17  0.21  0.12  0.09 0.10 0.16 0.15 0.02 0.11 0.23  0.25 1.00</code></pre>
</div>
</div>
<p>Our objective is to turn the R-matrix (correlation matrix) into an output which represents the degree to which each observed variable contributes to a component.</p>
<p>Principal components are derived through an eigen-decomposition of the correlation matrix. This process involves re-expressing the matrix in terms of its eigenvectors and eigenvalues. The <strong>eigenvectors</strong> define the directions (or axes) of the new feature space, while the corresponding <strong>eigenvalues</strong> indicate the amount of variance explained by each component.</p>
<section id="pc1" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="pc1"><span class="header-section-number">7.2.1</span> PC1</h3>
<ul>
<li>Eigenvector and eigenvalue for PC1</li>
</ul>
<p>The first eigenvector (<span class="math inline">\(\alpha_{11}, \alpha_{21}, ..., \alpha_{p1}\)</span>):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.225 0.239 0.214 0.226 0.220 0.173 0.240 0.207 0.175 0.179 0.251 0.250
[13] 0.220 0.214 0.242 0.234 0.176 0.185 0.173 0.141 0.123 0.146 0.149 0.140
[25] 0.166</code></pre>
</div>
</div>
<p>The corresponding eigenvalue, <span class="math inline">\(\lambda_{1}\)</span> is:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.365</code></pre>
</div>
</div>
<ul>
<li>Loadings of PC1</li>
</ul>
<p>Now, we are ready to calculate the loadings <span class="math inline">\(\phi_{11}, \phi_{21},..., \phi_{p1}\)</span> of the first principal component according to the formula:</p>
<p><span class="math display">\[\phi_{i1} = \alpha_{i1} \sqrt{\lambda_{1}}\]</span></p>
<p>where <span class="math inline">\(i= 1,...p\)</span>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.52 0.55 0.49 0.52 0.51 0.40 0.56 0.48 0.40 0.42 0.58 0.58 0.51 0.50 0.56
[16] 0.54 0.41 0.43 0.40 0.33 0.29 0.34 0.35 0.33 0.38</code></pre>
</div>
</div>
</section>
<section id="pc2" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="pc2"><span class="header-section-number">7.2.2</span> PC2</h3>
<ul>
<li>Eigenvector and eigenvalue for PC2</li>
</ul>
<p>The second eigenvector (<span class="math inline">\(\alpha_{12}, \alpha_{22}, ..., \alpha_{p2}\)</span>):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] -0.224 -0.212 -0.201 -0.265 -0.221 -0.156 -0.082 -0.308 -0.212 -0.245
[11]  0.240  0.287  0.173  0.079  0.143 -0.005  0.159  0.093  0.025  0.168
[21]  0.022  0.151  0.309  0.284  0.237</code></pre>
</div>
</div>
<p>The corresponding eigenvalue, <span class="math inline">\(\lambda_{2}\)</span> is:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.706</code></pre>
</div>
</div>
<ul>
<li>Loadings of PC2</li>
</ul>
<p>Now, we are ready to calculate the loadings <span class="math inline">\(\phi_{12}, \phi_{22},..., \phi_{p2}\)</span> of the second principal component according to the formula:</p>
<p><span class="math display">\[\phi_{i2} = \alpha_{i2} \sqrt{\lambda_{2}}\]</span></p>
<p>where <span class="math inline">\(i= 1,...p\)</span>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] -0.29 -0.28 -0.26 -0.35 -0.29 -0.20 -0.11 -0.40 -0.28 -0.32  0.31  0.38
[13]  0.23  0.10  0.19 -0.01  0.21  0.12  0.03  0.22  0.03  0.20  0.40  0.37
[25]  0.31</code></pre>
</div>
</div>
<p>The same procedure can be applied to calculate the loadings of the third principal component (PC3), the fourth component (PC4) and so on for subsequent components. Therefore, the loadings are scaled versions of eigenvectors that reflect both direction and strength of association.</p>
</section>
</section>
<section id="eigenvalues-and-variance" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="eigenvalues-and-variance"><span class="header-section-number">7.3</span> Eigenvalues and variance</h2>
<p>A fundamental aspect of principal component analysis (PCA) is understanding how eigenvalues relate to the variance in the dataset.</p>
<p>Each of the 25 eigenvectors has an associated eigenvalue, <span class="math inline">\(\lambda_1, \lambda_2, ... \lambda_p\)</span>, as shown below:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] 5.3654707 1.7059541 1.5384132 1.2206643 1.0777632 1.0395105 1.0223027
 [8] 0.9764029 0.9456935 0.9039208 0.8420446 0.8298040 0.7462031 0.7344016
[15] 0.6934445 0.6803484 0.6360415 0.6105103 0.5829854 0.5460390 0.5059900
[22] 0.4808372 0.4546453 0.4498703 0.4107389</code></pre>
</div>
</div>
<p>The sum of the eigenvalues will equal the number of variables in the data set:</p>
<p><span class="math display">\[\lambda_1 + \lambda_2 + \lambda_3 + ...+ \lambda_p = 5.37 + 1.71 + 1.54 +...+ 0.41 = 25\]</span></p>
<p>To determine the proportion of variance explained by the first principal component (i.e., direction by that component), we use the following formula:</p>
<p><span class="math display">\[\frac{\lambda_1}{\lambda_1 + \lambda_2 + \lambda_3 + ...+ \lambda_p} = \frac{5.37}{25} = 0.215 \ or \ 21.5\%\]</span></p>
<p>Similarly, the explained variance by the second principal component is:</p>
<p><span class="math display">\[\frac{\lambda_2}{\lambda_1 + \lambda_2 + \lambda_3 + ...+ \lambda_p} = \frac{1.71}{25} = 0.068 \ or \ 6.8\%\]</span></p>
<p>Note that the first component captures the maximum variance, the second captures the next highest variance orthogonal to the first, and so on.</p>
</section>
<section id="steps-in-the-process-of-pca" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="steps-in-the-process-of-pca"><span class="header-section-number">7.4</span> Steps in the process of PCA</h2>
<ul>
<li><p><strong>Prepare the Data:</strong> Create a dataframe where any items are scaled in the same direction (e.g., negatively worded items are reverse scored).</p></li>
<li><p><strong>Evaluate Assumptions:</strong> Assess the suitability of the data for PCA using diagnostic tests such as the Kaiser-Meyer-Olkin (KMO) measure of sampling adequacy and Bartlett’s test of sphericity. These tests determine whether the correlation matrix is appropriate for component extraction.</p></li>
<li><p><strong>Determine the Number of Components:</strong> Identify how many components to extract, guided by criteria such as eigenvalues greater than one, scree plot inspection, or parallel analysis. These components often correspond to underlying subscales.</p></li>
<li><p><strong>Extract and Rotate Components:</strong> Perform the extraction of components through an iterative process. Explore both orthogonal (uncorrelated) and oblique (correlated) rotation methods to enhance interpretability. Adjust the number of components and rotation type as needed to arrive at a theoretically meaningful and statistically sound solution.</p></li>
</ul>
</section>
<section id="example-of-grms-stress-appraisal" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="example-of-grms-stress-appraisal"><span class="header-section-number">7.5</span> Example of GRMS Stress Appraisal</h2>
<p>On the Jamovi top menu navigate to</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  A(Analyses) -.-&gt; B(Factor) -.-&gt; C(Principal Component Analysis)
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>as shown below (<a href="#fig-mlinear30" class="quarto-xref">Figure&nbsp;<span>7.3</span></a>).</p>
<div id="fig-mlinear30" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear30-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear30.png" class="img-fluid figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear30-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.3: Select from Factor the Principal Component Analysis.
</figcaption>
</figure>
</div>
<p>The <em>Principal Component Analysis box</em> opens (<a href="#fig-mlinear30" class="quarto-xref">Figure&nbsp;<span>7.3</span></a>). From the left-hand pane drag all the variables into the <em>Variables</em> field on the right-hand side, as shown below (<a href="#fig-mlinear26" class="quarto-xref">Figure&nbsp;<span>7.4</span></a>):</p>
<div id="fig-mlinear26" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear26-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear26.png" class="img-fluid figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear26-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.4: Principal Component Analysis box options. Drag and drop the variables in the fields on the right-hand side.
</figcaption>
</figure>
</div>
<p>All variables in the dataset are on the same scale (Likert scale).</p>
<section id="assumptions" class="level3" data-number="7.5.1">
<h3 data-number="7.5.1" class="anchored" data-anchor-id="assumptions"><span class="header-section-number">7.5.1</span> Assumptions</h3>
<p>From the <strong>Assumption Checks</strong>, tick both boxes: Bartlett’s test of sphericity and KMO measure of Sampling Adequacy.</p>
<div id="fig-mlinear27" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear27-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear27.png" class="img-fluid figure-img" style="width:40.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear27-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.5: Assumptions for PCA.
</figcaption>
</figure>
</div>
<ul>
<li>Bartlett’s test of sphericity</li>
</ul>
<p>Bartlett’s test examines the null hypothesis that the correlation matrix is an identity matrix—meaning all the variables are uncorrelated (i.e., the off-diagonal elements are zero). A significant result (p &lt; 0.05) indicates that the correlation matrix significantly differs from an identity matrix, suggesting that the variables share enough correlation to justify the use of principal component analysis (PCA).</p>
<div id="fig-mlinear29" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear29-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear29.png" class="img-fluid figure-img" style="width:30.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear29-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.6: Bartlett’s test.
</figcaption>
</figure>
</div>
<p>Our Bartlett’s test is significant: <span class="math inline">\(\chi^2 = 1217\)</span> (p&lt;0.001). This means that our sample correlation matrix is statistically significantly different than an identity matrix and, therefore, supports a component analytic approach for investigating the data.</p>
<ul>
<li>Kaiser-Meyer-Olkin (MKO) index of Sampling Adequacy</li>
</ul>
<p>The <strong>Kaiser-Meyer-Olkin</strong> index (KMO) is an index of <em>sampling adequacy</em> that varies between 0 and 1. Kaiser’s 1974 recommendations were:</p>
<ul>
<li>bare minimum of 0.5</li>
<li>values between 0.5 and 0.7 as mediocre</li>
<li>values between 0.7 and 0.8 as good</li>
<li>values between 0.8 and 0.9 as great</li>
<li>values above 0.9 are superb</li>
</ul>
<p>If the KMO is below the recommendations, we should probably collect more data to see if it can achieve a satisfactory value.</p>
<div id="fig-mlinear28" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear28-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear28.png" class="img-fluid figure-img" style="width:30.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear28-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.7: Kaiser-Meyer-Olkin measure.
</figcaption>
</figure>
</div>
<p>The Kaiser–Meyer–Olkin (KMO) measure verified the sampling adequacy for the analysis KMO = 0.85, which is considered “great”. Additionally, all individual KMO values were above 0.74—well above the acceptable threshold of 0.50.</p>
</section>
<section id="specify-the-number-of-components" class="level3" data-number="7.5.2">
<h3 data-number="7.5.2" class="anchored" data-anchor-id="specify-the-number-of-components"><span class="header-section-number">7.5.2</span> Specify the Number of Components</h3>
<p>Our decisions on how many components to keep can be guided by several methods:</p>
<ul>
<li><p>Cumulative variance explained – Retain enough components to account for a desired proportion of total variance.</p></li>
<li><p>Parallel analysis – Compare the observed eigenvalues with those obtained from randomly generated data to determine which components are meaningful.</p></li>
<li><p>Kaiser’s criterion – Retain components with <strong>eigenvalues greater than 1</strong>.</p></li>
<li><p>Theoretical justification – Retain components that align with prior knowledge, conceptual frameworks, or hypotheses relevant to the domain of study (fixed number).</p></li>
</ul>
<p>Jamovi allows users to choose the number of components based on parallel analysis, eigenvalues, or by manually specifying a fixed number.</p>
<div id="fig-mlinear45" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear45-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear45.png" class="img-fluid figure-img" style="width:35.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear45-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.8: Choose a method to define the number of components.
</figcaption>
</figure>
</div>
<p>Additionally, a scree plot displays the eigenvalues associated with each principal component in descending order. It is used to visually identify the “elbow point”—the point at which the rate of decline in eigenvalues noticeably levels off. This point suggests the optimal number of components to retain, as additional components contribute relatively little to explaining variance.</p>
<div id="fig-mlinear44" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear44-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear44.png" class="img-fluid figure-img" style="width:30.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear44-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.9: Scree plot.
</figcaption>
</figure>
</div>
<div id="fig-mlinear31" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear31-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear31.png" class="img-fluid figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear31-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.10: Scree plot determining the number of components based on parallel analysis.
</figcaption>
</figure>
</div>
<div id="fig-mlinear32" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear32-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear32.png" class="img-fluid figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear32-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.11: Scree plot determining the number of components based on Kaiser’s criterion.
</figcaption>
</figure>
</div>
<p>In our example, parallel analysis suggests retaining 3 components (<a href="#fig-mlinear31" class="quarto-xref">Figure&nbsp;<span>7.10</span></a>), while Kaiser’s criterion indicates 7 components (<a href="#fig-mlinear32" class="quarto-xref">Figure&nbsp;<span>7.11</span></a>).</p>
<p>If we select three principal components based on parallel analysis, we observe that the uniqueness of some variables is relatively high (e.g., Obj6 Uniqueness = 0.8). Uniqueness refers to the proportion of a variable’s variance that is not explained by the retained components. Therefore, if a variable has high uniqueness (close to 1), it indicates that the variable is poorly explained by the selected number of components.</p>
<div id="fig-mlinear48" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear48-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear48.png" class="img-fluid figure-img" style="width:45.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear48-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.12: The uniqueness of some variables is relatively high when selecting three principal components.
</figcaption>
</figure>
</div>
<p>If our scale construction includes a priori or planned subscales, we expect the observed variables to reflect the following conceptual dimensions:</p>
<ul>
<li>Assumptions of Beauty and Sexual Objectification</li>
<li>Silenced and Marginalized</li>
<li>Strong Woman Stereotype</li>
<li>Angry Woman Stereotype</li>
</ul>
<p>Therefore, guided by prior knowledge and theoretical considerations, we have decided to retain the first four components for further analysis.</p>
<div id="fig-mlinear43" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear43-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear43.png" class="img-fluid figure-img" style="width:35.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear43-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.13: Select four principal components.
</figcaption>
</figure>
</div>
</section>
<section id="component-rotation" class="level3" data-number="7.5.3">
<h3 data-number="7.5.3" class="anchored" data-anchor-id="component-rotation"><span class="header-section-number">7.5.3</span> Component Rotation</h3>
<p>Rotation in PCA redistributes the variance between components, making the loadings more distinct and interpretable. In other words, rotation typically causes each observed variable to load highly on precisely one component.</p>
<p>There are two main types of rotation, and the choice between them depends on theoretical considerations:</p>
<ul>
<li><strong>Orthogonal Rotation:</strong> Use this if you believe the components are independent or unrelated.
<ul>
<li>Varimax is the most common orthogonal rotation method.</li>
</ul></li>
<li><strong>Oblique Rotation:</strong> Use this if you believe the components are correlated or related.
<ul>
<li>Oblimin and Promax are common oblique rotation methods.</li>
</ul></li>
</ul>
<p><strong>Which method should we choose?</strong></p>
<ul>
<li><p>Orthogonal rotation is often considered “easier” because it minimizes cross-loadings (i.e., it reduces the correlation between components). However, this assumes that the components are truly independent, which may not always be the case.</p></li>
<li><p>Can you think of a measure where the subscales would <em>not</em> be correlated? In many real-world cases, components are likely to be correlated, which might suggest that oblique rotation is the better choice.</p></li>
</ul>
</section>
</section>
<section id="varimax-rotation" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="varimax-rotation"><span class="header-section-number">7.6</span> Varimax rotation</h2>
<p>Select the <strong>Varimax</strong> rotation method:</p>
<div id="fig-mlinear41" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear41-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear41.png" class="img-fluid figure-img" style="width:30.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear41-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.14: Select the Varimax method of rotation.
</figcaption>
</figure>
</div>
<p>After rotation, there are four clear components/scales (NOTE: In the unrotated method, most variables loaded on the first component).</p>
<div id="fig-mlinear33" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear33-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear33.png" class="img-fluid figure-img" style="width:55.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear33-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.15: Loadings with orthogonal rotation.
</figcaption>
</figure>
</div>
<p>There is clear (or at least reasonable) component/scale membership for each variable. This table lists all component loadings that are greater than 0.30. When an observed variable has multiple component loadings listed, we inspect it for “cross-loading.” We observe cross-loadings with the following observed variables: Obj6, Marg6, and Ang1.</p>
<p>It is important to note that in PCA with <strong>orthogonal</strong> rotation (such as Varimax), the factor loadings can be interpreted as <strong>correlation coefficients</strong> between the original observed variables and the rotated components.</p>
<p>&nbsp;</p>
<p>Moreover, under the <strong>Additional Output</strong> section, select <em>Component summary</em>:</p>
<div id="fig-mlinear46" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear46-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear46.png" class="img-fluid figure-img" style="width:30.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear46-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.16: Select component summary.
</figcaption>
</figure>
</div>
<p><a href="#fig-mlinear35" class="quarto-xref">Figure&nbsp;<span>7.17</span></a> presents the percentage of variance in the variable set that is captured by the derived components after Varimax rotation.</p>
<div id="fig-mlinear35" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear35-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear35.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear35-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.17: Variance with orthogonal rotation.
</figcaption>
</figure>
</div>
<p>The SS Loadings column represents the eigenvalues for each component after Varimax rotation, with Principal Component 1 explaining 13.2%, Principal Component 2 explaining an additional 11.7%, Principal Component 3 explaining an additional 8.2%, and Principal Component 4 explaining an additional 6.2%, resulting a cumulative variance of 39.3%.</p>
<p>The path diagram follows:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pca_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="oblique-rotation" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="oblique-rotation"><span class="header-section-number">7.7</span> Oblique rotation</h2>
<div id="fig-mlinear42" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear42-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear42.png" class="img-fluid figure-img" style="width:30.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear42-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.18: Select the Oblimin method of rotation.
</figcaption>
</figure>
</div>
<p><a href="#fig-mlinear36" class="quarto-xref">Figure&nbsp;<span>7.19</span></a> shows the loadings of the principal components after rotation.</p>
<div id="fig-mlinear36" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear36-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear36.png" class="img-fluid figure-img" style="width:55.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear36-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.19: Loadings with oblique rotation.
</figcaption>
</figure>
</div>
<p><a href="#fig-mlinear37" class="quarto-xref">Figure&nbsp;<span>7.20</span></a> presents the percentage of variance in the variable set that is captured by the derived components after Oblimin rotation.</p>
<div id="fig-mlinear37" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear37-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear37.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear37-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.20: Variance with oblique rotation.
</figcaption>
</figure>
</div>
<p>The SS Loadings column represents the eigenvalues for each component after Oblimin rotation, with Principal Component 1 explaining 13.3%, Principal Component 2 explaining an additional 11.6%, Principal Component 3 explaining an additional 8.2%, and Principal Component 4 explaining an additional 6.2%, resulting a cumulative variance of 39.3%.</p>
<p>&nbsp;</p>
<p>Moreover, under the <strong>Additional Output</strong> section, select <em>Component correlations</em>:</p>
<div id="fig-mlinear47" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear47-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear47.png" class="img-fluid figure-img" style="width:30.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear47-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.21: Select Component correlations.
</figcaption>
</figure>
</div>
<p>The Inter-Component Correlation Matrix reveals that the four components are positively correlated with each other, with correlations ranging from 0.09 to 0.35 (<a href="#fig-mlinear38" class="quarto-xref">Figure&nbsp;<span>7.22</span></a>).</p>
<div id="fig-mlinear38" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear38-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear38.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear38-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.22: Inter-Component Correlation Matrix.
</figcaption>
</figure>
</div>
<p>The path diagram follows:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="pca_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Note that this path diagram includes links with numerical values between components, representing the correlation coefficients among them. In contrast, orthogonal rotation assumes the components are uncorrelated, so such links do not appear.</p>
</section>
<section id="component-scores" class="level2" data-number="7.8">
<h2 data-number="7.8" class="anchored" data-anchor-id="component-scores"><span class="header-section-number">7.8</span> Component scores</h2>
<p>Component scores represent each observation’s position on the extracted components. They are calculated as weighted combinations of the original variables, using the component loadings derived from PCA. After rotation, these scores reflect the rotated solution, providing insight into how each case (e.g., participant) scores on the newly defined components.</p>
<p>To compute the component scores, click on the Save dropdown menu and select the Component scores option (<a href="#fig-mlinear40" class="quarto-xref">Figure&nbsp;<span>7.23</span></a>).</p>
<div id="fig-mlinear40" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear40-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear40.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear40-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.23: From the Save dropdown menu select the Component scores.
</figcaption>
</figure>
</div>
<p>New variables have been created, each containing the component scores for the extracted components (<a href="#fig-mlinear39" class="quarto-xref">Figure&nbsp;<span>7.24</span></a>).</p>
<div id="fig-mlinear39" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlinear39-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mlinear39.png" class="img-fluid figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlinear39-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.24: Component scores after Oblimin rotation.
</figcaption>
</figure>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./linear2.html" class="pagination-link" aria-label="Linear regression (2)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Linear regression (2)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ma1.html" class="pagination-link" aria-label="Systematic Review and Meta-analysis (1)">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Systematic Review and Meta-analysis (1)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Copyright 2024, Konstantinos I. Bougioukas. License: <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivs 4.0</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a><sup>®</sup></p>
</div>
  </div>
</footer>




</body></html>